#!/bin/sh



run() {
  rsync -av \
    --delete \
    --delete-excluded \
    --exclude=".git*" \
    --exclude="update" \
    . /etc/nixos
}

git crypt unlock && run && sudo nixos-rebuild switch 
git crypt lock
